<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class OmniUserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('omni_user')->insert([
            [
                'userid' => 1,
                'username' => 'Veeko Lam',
                'password' => 'veeko',
                'usercode' => 'veeko',
                'user_type' => 1,
                'user_email' => 'veeko@majestic.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
            [
                'userid' => 2,
                'username' => 'Ricky Chow',
                'password' => 'rickyokita',
                'usercode' => 'rickyokita',
                'user_type' => 1,
                'user_email' => 'rickyokita@gmail.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
            [
                'userid' => 3,
                'username' => 'Lucas Wong',
                'password' => 'lucaswong',
                'usercode' => 'lucaswong',
                'user_type' => 1,
                'user_email' => 'lucas@gmail.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
            [
                'userid' => 4,
                'username' => 'James Chan',
                'password' => 'jameschan',
                'usercode' => 'jameschan',
                'user_type' => 1,
                'user_email' => 'jamescha@gmail.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
            [
                'userid' => 5,
                'username' => 'arbeeTest',
                'password' => 'arbeetest',
                'usercode' => 'arbeetest',
                'user_type' => 2,
                'user_email' => 'arbeetest@gmail.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
            [
                'userid' => 6,
                'username' => 'algoTest',
                'password' => 'algotest',
                'usercode' => 'algotest',
                'user_type' => 3,
                'user_email' => 'algo1@gmail.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
            [
                'userid' => 7,
                'username' => 'michaelTest',
                'password' => 'michaeltest',
                'usercode' => 'michaeltest',
                'user_type' => 2,
                'user_email' => 'michael@gmail.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
            [
                'userid' => 8,
                'username' => 'yipTest',
                'password' => 'yiptest',
                'usercode' => 'yiptest',
                'user_type' => 2,
                'user_email' => 'yip@gmail.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
            [
                'userid' => 9,
                'username' => 'dragonTest',
                'password' => 'dragontest',
                'usercode' => 'dragontest',
                'user_type' => 2,
                'user_email' => 'dragon@gmail.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
            [
                'userid' => 10,
                'username' => 'maskaTest',
                'password' => 'maskatest',
                'usercode' => 'maskatest',
                'user_type' => 2,
                'user_email' => 'maska@gmail.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
            [
                'userid' => 11,
                'username' => 'jacobTest',
                'password' => 'jacobtest',
                'usercode' => 'jacobtest',
                'user_type' => 2,
                'user_email' => 'jacob@gmail.com',
                'created_date' => '2017-07-13 00:00:00',
                'created_by' => 2,
                'modified_date' => '2017-07-13 00:00:00',
                'modified_by' => 2,
                'status' => 1,
            ],
        ]);
    }
}
